const jobPositions = [
	{ label: 'Student' },
	{ label: 'Software Engineer' },
	{ label: 'Full Stack Developer' },
	{ label: 'Frontend Developer' },
	{ label: 'Backend Developer' },
	{ label: 'Data Scientist' },
	{ label: 'Data Engineer' },
	{ label: 'Machine Learning Engineer' },
	{ label: 'AI Research Scientist' },
	{ label: 'DevOps Engineer' },
	{ label: 'System Administrator' },
	{ label: 'Network Engineer' },
	{ label: 'Database Administrator' },
	{ label: 'Security Analyst' },
	{ label: 'Cybersecurity Engineer' },
	{ label: 'IT Support Specialist' },
	{ label: 'IT Project Manager' },
	{ label: 'UI/UX Designer' },
	{ label: 'Web Designer' },
	{ label: 'Mobile App Developer' },
	{ label: 'QA Engineer' },
	{ label: 'Business Analyst' },
	{ label: 'Technical Writer' },
	{ label: 'Cloud Architect' },
	{ label: 'Solutions Architect' },
	{ label: 'Information Security Manager' },
];

export default jobPositions;
